---
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint with golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          args: --timeout 5m

      - name: Check code formatting
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            exit 1
          fi

      - name: Static analysis
        run: go vet ./...

      - name: Run tests
        run: |
          go test -v ./... -coverprofile=coverage.out
